spring.application.name=service-desk-api

spring.datasource.url=jdbc:postgresql://localhost:5432/servicedesk
spring.datasource.username=servicedesk

spring.jpa.hibernate.ddl-auto=validate

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000