CREATE TABLE    teams (
    id BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    email VARCHAR(255) NOT NULL UNIQUE ,
    full_name VARCHAR(150) NOT NULL ,
    team_id BIGINT ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_users_team
                  FOREIGN KEY (team_id) REFERENCES teams (id)
                  ON DELETE SET NULL

);

CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    title VARCHAR(200) NOT NULL ,
    description TEXT NOT NULL ,
    status VARCHAR(20) NOT NULL ,
    category  VARCHAR(20) NOT NULL ,
    requester_id BIGINT NOT NULL ,
    assignee_id BIGINT ,
    team_id BIGINT ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_tickets_status
        CHECK (status IN ('NEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),

    CONSTRAINT chk_tickets_category
        CHECK (category IN ('NETWORK', 'HARDWARE', 'ACCESS', 'SOFTWARE')),

    CONSTRAINT fk_tickets_requester
                     FOREIGN KEY (requester_id) REFERENCES users (id)
                     ON DELETE RESTRICT ,

    CONSTRAINT fk_tickets_assignee
        FOREIGN KEY (assignee_id) REFERENCES users (id)
            ON DELETE SET NULL ,

    CONSTRAINT fk_tickets_team
        FOREIGN KEY (team_id) REFERENCES teams (id)
            ON DELETE SET NULL
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    body TEXT NOT NULL ,
    ticket_id BIGINT NOT NULL ,
    author_id BIGINT NOT NULL ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_comments_ticket
            FOREIGN KEY (ticket_id) REFERENCES tickets (id)
                ON DELETE CASCADE ,

    CONSTRAINT fk_comments_author
        FOREIGN KEY (author_id) REFERENCES users (id)
            ON DELETE RESTRICT
);
